<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="46159" started-at="2015-02-02T20:57:45Z" finished-at="2015-02-02T20:58:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="46159" started-at="2015-02-02T20:57:45Z" finished-at="2015-02-02T20:58:32Z">
      <class name="com.scholastic.sso.misc.StoriaSamplerEReaderTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.scholastic.sso.misc.StoriaSamplerEReaderTest@5a61f5df]" name="beforeTest" is-config="true" duration-ms="5832" started-at="2015-02-02T15:57:45Z" finished-at="2015-02-02T15:57:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="storiaSamplerEReaderTest(java.util.Hashtable)[pri:0, instance:com.scholastic.sso.misc.StoriaSamplerEReaderTest@5a61f5df]" name="storiaSamplerEReaderTest" duration-ms="38161" started-at="2015-02-02T15:57:52Z" data-provider="MiscDataProvider" finished-at="2015-02-02T15:58:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=Y}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.scholastic.sso.misc.StoriaSamplerEReaderTest.storiaSamplerEReaderTest(StoriaSamplerEReaderTest.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- storiaSamplerEReaderTest -->
        <test-method status="PASS" signature="takeScreenShotOnFailure(org.testng.ITestResult)[pri:0, instance:com.scholastic.sso.misc.StoriaSamplerEReaderTest@5a61f5df]" name="takeScreenShotOnFailure" is-config="true" duration-ms="1042" started-at="2015-02-02T15:58:31Z" finished-at="2015-02-02T15:58:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=storiaSamplerEReaderTest status=FAILURE method=StoriaSamplerEReaderTest.storiaSamplerEReaderTest(java.util.Hashtable)[pri:0, instance:com.scholastic.sso.misc.StoriaSamplerEReaderTest@5a61f5df] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenShotOnFailure -->
      </class> <!-- com.scholastic.sso.misc.StoriaSamplerEReaderTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
